language: android
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    - $HOME/.android/build-cache

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
before_install:
- sh script/decrypt.sh
- chmod +x gradlew
- chmod +rx app
skip_cleanup: true
script:
- sh script/build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: sh script/deploy.sh
  on:
    branch:
    - dev
    - master
env:
  global:
  - secure: fZdzfpe9yNbFLbZr/pV/7k1MkjA5BNJw5VAi8X/Q/0fKwuuQITjSMtAyWE3tP53JP3KIDyI+QrdX2GnFLHxTwPaSmYF41/+6/QIjRsvhH1kZaQ0cLQwNwLoGOLSKyPOCm3t8TJCFzpekEXKP3EemizPpDksVd8MBpDx2k8scxaE9JEJtxG8vKNQW5KGq7mzn0txgcLKyz6K23yJ2hHlGxusNRKDxc9F+YnjLp944/CFLToufUqN+01G+NxJYdqSSxDkMkd9NgEs+eoooSfrCHm/S2wTilzKNON7dX+f0ZVcgSlH2ObBR4xB1zvY/LMvt8pqckNB8nd9r/eSIoBmJbrcXvlnal8GuYF0epfm2df5GNjwvOR8lXTsK+t1EFral66yw+fDrCv87OuDXsBmXLyTg4sasg3dspUip5kArDKAtPaiAoRbfmo7E4/VDDQb347vn6eN6T/rTu5nwzz9SyVaD5w/YOoYsTPT6buHvNd+0F4bu/U2i8bLc5XplZKmyHHfzGG0mJMH5MAqhDMHB8QJCSqiT+h0dmc0YMejqWDmXi3as5unrBElOTuzZrVyllyLXco2rom6Z+vg5lk4TwCBu4Jz+J94TXM9tvjjehUY9xTarzBD9mqoEAhoitijCHk2k8fRP4QnQ5KCwjm7U+pL3imovXkryvbZtYlsaSag=
  - secure: h73EGkIPZTuqlyoVmEPllYFhYdDwuk9U0qkfv26p0nMkfDm5LQSIvsmzVGScvw9RMvcI678qstdVkAshcGzCC1cC/TwvhiMgdAZ/LGKPyGAuK7qCirCHBKyv3PcA8qKOHcxPgQR2xyxbazHnaK7CWnFrcdugHu820r8MIbXUEYiKnbIkQ4DeQaZVi5UV1wuR4fG+iZGpVBtqHae/zufUJ49VZqAL0HMhvCM5eqFUuR9W8MJFHGbTjhtekc3+Rw0wwBY8tuqN6Rp664QrdTNF93r5phYlMMOfxA743cXzNKG8VAnWDSjTolMEGxjEGmBtHg9u2k6UWIR3PteV48yLsc6swiT0516TlFbrLwJjALkJiFMLEgB0aukUbagHXO1Bb8OAhpb8Z/tfk0cVFdc74s3tqLjzUezLx7626nyLpsOxXtDhTkqFCURM1RiVPcVkTRza2lr+QmlD5tZkin1suieTQJFFiEu9iz+57T9mGeH56ByEfKjLCkLkIaPKG+6ZVoG8ooEkmJ2aD0yT342uFrEjx08HREqfPBoaniwLks+utD3Pz9CWnM6ZsaJrLuJVXxdvwAc+pMugCvuNCf3MWNSSomT/CPdx94z+8SgJKKMjmsm/fN9xZpEglJEMyPf8fKCBGd/9tMoD3+yNUs4uYlkVdkyPKemsjarGiF7+eqU=
  - secure: qPmAyj0trhNkFe2xRP9fWiKNFKYEy24q+rkUTAMWG7h0KPfVy3y90qzwtfvYIAiPa9jluRalwDG4NtEv3xWu+hzpBBJMYWaKzUc6IdCNjRKeHEua8uWUHvDj6clLsFWAMDrSTR9Rx8n20enrgMOzxoJnuhgpFomKfU+ytSS0nRGoWK4llsuvQcneaaMtdhgAPmKhKMAcgQU18Fw/pEuzc/87fMGXLAjNLKO7k/6M26tGQP9G1FAQIGg4vzsFcbXaVIpFQurC3Rdhy/gAvSn194yUJyIAAk+d2huPmGQP7G3iFHU6pYnyqMNUfyvhdQBnrYFAPjF7prgRLkfWI4Yy4PeesRzvhQcK34G12afy8gu+CBeAueg8xwPpFUAG6iVAtzRFfmeosYeZzRCjnVas6mHLKDL0KFZPnmKm1Z3plDZiXdGH7Mi93qkZ0o0HaTyrhPQ7PCYkRemriTlPdPb0yJcl7iP55zAdmb9KPCyrHYR45VvBQ3gQmY8YQoq+P/XHhid+kKg4HqAXJW/6Q3Ns6hgI5jwlYtxtCGEluCn3FbNexy14X5uj5UG60P2R3x5l4yVdCTOgiwek17D0/SOk6QE90fX9eIm2KSl0uqtD7MmUDMHzMYv50h0cQZrnhuslosXrQtGeLUvI46XWqRo2RL0ybTC/T0jSCGcj05YEXNQ=
  - secure: X6kcBHBbtdanH8zzt8gRL3H6W3eZqMnOZmy+NQ5DgO7xRgmjDYY8XjrBBwFNBDDVjVzuWRlbe3ITG+E86VWM6M721b21nMn983SazYOJdMn7G8Ts6/S6piTbFqd1ZyVm9X+1ZiORSd+tmHtuWAHS1pWE6l1e6yGTPl78JsmO/9F6M4bbyWjEKJCEDdpo/P4SpTJyDUI77BxHB3n2blBgicqt6azHM/AU/v48xRbxwCLpYP4o/azyyHUrFHjslistvXFZv1AbX4p14CfOmddpLRqVmfuRebLqmIg5kEL1CsUI5W53vrXfCmTGjRx1PPTB4h+n41070daEvkY7517++F8yfmIR/nlDZECbZij6YN3KX0wwGnlkgVxJmKiRLWRUtCIifMZW/ykvCifkybxNaZKs3WnZCTdu0IhOY1ST0gEkBnGrQjGQD5omEttGqQZ2woQ03lgaltcY4ou6Tn/m3XxkqJRamLHshPKwe6d+PIIFA1vD5Bgtr7OzFBBSWJjYe/W3y7JYkuojeMzOi7VIjOLCyOSrMFZE2gI3W7dYW//4eM2qgG/xDJZLnLEMo+hyoD0Zl2Sx/EwzyL/zck0XSLtYlm5Axk92ol67LgP4eegqkwMOUJ3Dydciik7s+9DzSWV4row4uATAZC10RWK6ZJsLXBcyz3sQ/CrNqrtiB7I=
