language: android
script: 
  - export BUILD_BRANCH_NAME=$TRAVIS_BRANCH
  - "sh script/build.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_COMMIT_MESSAGE"
  - if [ "$TRAVIS_BRANCH" = "dev-jspiner" ]; then sh script/deploy.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_COMMIT_MESSAGE; fi
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then sh script/deploy.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_COMMIT_MESSAGE; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sh script/deploy.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_COMMIT_MESSAGE; fi