language: android
before_install:
- openssl aes-256-cbc -K $encrypted_27342c7446d8_key -iv $encrypted_27342c7446d8_iv
  -in google-services.json.enc -out app/google-services.json -d
- openssl aes-256-cbc -K $encrypted_27342c7446d8_key -iv $encrypted_27342c7446d8_iv
  -in calysigningkey.jks.enc -out calysigningkey.jks -d
- chmod +x gradlew
- chmod +rx app
skip_cleanup: true
script:
- sh script/build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: sh script/deploy.sh
  on:
    branch:
    - dev
    - master
