language: android
script: "sh script/build.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_COMMIT_MESSAGE"
deploy:
  provider: script
  skip_cleanup: true
  script: "sh script/deploy.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_COMMIT_MESSAGE"
  on:
    all_branches: true