language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_27342c7446d8_key -iv $encrypted_27342c7446d8_iv
  -in google-services.json.enc -out app/google-services.json -d
- chmod +x gradlew
- chmod +rx app 
skip_cleanup: true
script: 
  - "sh script/build.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_COMMIT_MESSAGE"
deploy:
provider: script
script: "sh script/deploy.sh"
on:
  branch:
    - dev-jspiner
    - dev
    - master