language: android
before_install:
- sh script/decrypt.sh
- chmod +x gradlew
- chmod +rx app
skip_cleanup: true
script:
- sh script/build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: sh script/deploy.sh
  on:
    branch:
    - dev
    - master
